AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  builder-pattern-service
  
  FastAPI service for analyzing code and suggesting builder patterns

Globals:
  Function:
    Timeout: 180
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'POST, OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"

Resources:
  BuilderPatternFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:builder-pattern-service-secrets*'
      Environment:
        Variables:
          OPENAI_API_KEY: !Sub '{{resolve:secretsmanager:${AWS::StackName}-secrets:SecretString:OPENAI_API_KEY}}'
      Events:
        AnalyzeCode:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

  # Resource Group for Application Insights
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  BuilderPatternApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze/"
  BuilderPatternFunction:
    Description: Lambda Function ARN
    Value: !GetAtt BuilderPatternFunction.Arn
  BuilderPatternFunctionRole:
    Description: IAM Role created for Builder Pattern function
    Value: !GetAtt BuilderPatternFunctionRole.Arn